# Server
MAXIMUM_ACCOUNTS = 2
SERVER_UUID = "SAZUGFASJIUGBIORFGISODBQPYIJGIOBASIBASU9"

# Communication Server
COMMUNICATION_IP = "127.0.0.1"
COMMUNICATION_PORT = 3458
FORMAT = "utf-8"
HEADER = 64
RECONNECT_TRIES = 3

# Webbrowser
BASE_URL = "https://www.conflictnations.com/"
BROWSER_GAME_LOADING_TIMEOUT = 120
SELENIUM_GRID_IP = "192.168.20.75"
SELENIUM_GRID_PORT = 4444

SHORT_SCAN_SORTED_DATA_SAVE = False

BOT_IP = "192.168.30.20"



DB_NAME = "testing"
DB_USERNAME = "testing"
DB_PASSWORD = "JGVCDwuwXvmO"
DB_IP = "192.168.20.75"
